---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
  enablePDB: false
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.4-1.1.1@sha256:9c9246cb8ba0332f7e1115def71329410657237db8ef104160a479a89c7e03a2
  instances: 1
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-postgres-secret
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: r2
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
    shared_preload_libraries:
      - vchord.so
  primaryUpdateStrategy: unsupervised
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
