---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-postgres-secret
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .IMMICH_POSTGRES_USER }}"
        password: "{{ .IMMICH_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: immich
