apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6aiIDWH2DCYw1w==,iv:JcWnTTFcv6skCQxOvwP8dqWMUPIewqvgE7ozzyBxWRY=,tag:XvIp0iybvYpRGTjRb/4peQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRlZVZnZHbFFyZXlHdjB4
        MkZOeGVEMndxblVBOUk3Vm1saXhEdUpPUDN3CmUycU5EcHRTTmVtMlc4N1RqWllL
        aTc2Y2RrbkRsN0NYdXhjeHdVQkNEMjAKLS0tIFEydkpiOFlsOHpKODBuWnE5NGpi
        Q25OSWF5Yk9mMzBLeGxhT1lkZUx0VEEK+TaCmrB/fPtATH1RIuNhuQnxrXB7B8Op
        uvs8wyACt8KZFihyozZHJZ9Q6HE50e0IWtC4uc3AFnhujE1H4b8F5Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:24:40Z"
  mac: ENC[AES256_GCM,data:7xFsOS382+m0gd333AVZpeVamc0sqttoR4ntIsskJoKsH3t9ujL8K+M4NOVIxJVaW3jeqYsRRRG3pQHW3qnMYRp9wRG3RG8vyKt8qjrSy6vCaLJWhqFc20NCkLUDeqfQPe9Qyu4PQAWSCkAp0qEskpRjlCb9VRi8aECfOBEosh0=,iv:aRr+AxhH/NmySFoGJO260ojDMwgdCnJed3dnLZXNdhQ=,tag:tstJ++qMLfa1CmRMbTxv6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
