apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:d3XBqvXJ3Qd5QXBoR05eJHzEcjDd0/l2W0KeqkGDLhM=,iv:lTm0gT5LGYOQwRCIpYW5AH3ZTOXw/5QwIHyNaomN2pE=,tag:0qEWGS0MnZFDd/KLh7itlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUk1nN1NYL0VyVDRPS0lV
        T3VlVGl1WW1kNEFzR2pYTUxFUERUczdZcGtnCjR3ZlVrMHBBRW5jUkY2T3BnaEMr
        dXMwcmk0U3VrSWlzazFhLzNPS3NoZ00KLS0tIC9kM1E5OE02QXVqNXEyc1Jxd1NO
        enJhWHJzNFpIT3BnVEw3dUFRV2R2L1kKTdXgtShcUn+uuOgri5am0OkDqe/tDKrD
        bJ5uMoSTUJPO2ifLRfrSMUSoUTNi+z2+CMfDxmBnWkUoSeCzpuu8WQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:24:40Z"
  mac: ENC[AES256_GCM,data:q+R+gZXd+wwHwCMCmXkR5zhhgrhAo5CWmE2p8zhkSOkfq4Wg9Q+5rC2jZyvZ2PQfLEigWFHhaikX1DJpGqrPw3opt2juweM3u1ZAqNysgOv/IqJ1mu3uPdqGtUBXEi5DrDgs5g0B0rSfYXv/UwAZRpqelpG+HWWlk/une117Nmo=,iv:mnMoyspvk3MqINEWjWOZOslD6sTY/3b14ij0X+YgxI0=,tag:zYt/HE40cwpogy0lQc0Esw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
