apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bklPV5zVHTlYo4ERoU7u9cLQe6qg3CZQ/M5naDiY+sO1z/fHGXTvqA==,iv:kozvvXUYNQG3mF88oFTsaJ3PQ0BKokKRrmwIGApvECo=,tag:PA3v0vUqY745ILcFnwmc9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTHF5MEZOZmxmdnAySi9s
        bzhNT1pvdTNIZGJDTGZPU0wybElscnZYNURZCm1HanJTemNQcVc1elg2em5WZWVJ
        YmFSWlcraXF6bFdPenE5V1NmamxoWFkKLS0tIGxKWFc0VXVXU1RXKzFKQVQ4NHI1
        TS9PMW15Ujc3b2VUZ003UlFaYnVUL2sKmjDh85ySFdvguEFYUp8uk2eFfsK6R6vM
        Y048Bw5ESdffQak1w+t/yKFsXOg8xAkQhIWGZsAlr1woP6SH7CXkfw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qeu5ft3kqvvwz2pkdmmxw7vsrr6gydegmm7km25rqvqexkhga9gq228h6z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:24:40Z"
  mac: ENC[AES256_GCM,data:vNSKDRm81lNuC1pwGxksI9dG37kVdKQCHS1dpxL63/BAjZSgwBjP+5WO5HdrFy+iu9ft0/PNe7kk8DhC0Ne602rZZW73NyApidEfDLaqg8/LqheE67x/Wi/D2igFakUDQHAo8Xy5/h4ZuQBq+SZw+YuncggLRYnOuBME/AngajM=,iv:wUBBkdXqI3VXzN4QCQ6e87dP7IegJnOrpUxVo+0pGyI=,tag:36L3OxCaCxGfKLuE7Dg3tg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
